apiVersion: apps/v1
kind: Deployment
metadata:
  name: pointage
spec:
  selector:
    matchLabels:
      app: pointage
  replicas: 2
  template:
    metadata:
      labels:
        app: pointage
    spec:
      containers:
        - name: pointage
          image: pointage:1.0
          imagePullPolicy: IfNotPresent
#          resources:
#            limits:
#              memory: "128Mi"
#              cpu: "500m"
          ports:
            - containerPort: 8080
